apiVersion: v1
kind: ConfigMap
metadata:
  name: simulator-conf
data:
  env: |
    MONGO_DSN=mongodb+srv://devradardb:mETI9DZKt2QkWN13@devradardb.ttnlq.mongodb.net/imersao-fsfc2?authSource=admin&replicaSet=DevRadarDB-shard-0&w=majority&readPreference=primary&appname=imersao-fsfc2&retryWrites=true&ssl=true
    KAFKA_CLIENT_ID=code-delivery
    KAFKA_BROKER=pkc-lzvrd.us-west4.gcp.confluent.cloud:9092
    KAFKA_CONSUMER_GROUP_ID=code-delivery
    KAFKA_SASL_USERNAME=AY4TGW3EZDLXYFCJ
    KAFKA_SASL_PASSWORD=G8wzZq1BCFHLv3+FER5uW2yUKQ81OFO91JApZ/Bs5Bdx49EJVyiFDjQMSPZnLzte